FROM balenalib/%%BALENA_MACHINE_NAME%%-debian

WORKDIR /usr/src


RUN apt-get update && apt-get install -yq --no-install-recommends \
    ruby-dev build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


RUN gem install fluentd --no-doc
#https://github.com/splunk/fluent-plugin-splunk-hec
RUN gem install fluent-plugin-splunk-hec

COPY . ./

CMD ["/bin/bash", "-c", "src/main.sh"]
